# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestsearcj():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testsearcj(self):
    self.driver.get("https://www.google.com/")
    self.driver.set_window_size(1280, 680)
    time.sleep(2)
    element = self.driver.find_element(By.CSS_SELECTOR, ".gb_Ca")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.NAME, "q").send_keys("selenium")
    time.sleep(2)
    self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(3) > .tF2Cxc .LC20lb").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".selenium-webdriver:nth-child(1)").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".td-content").click()
  
